name: music_companion_ui
description: "A new Flutter project."
publish_to: 'none' # This line prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.2
  animated_background: ^2.0.0
  http: ^1.3.0
  lottie: ^2.7.0
  audioplayers: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/animations/melody_flow.json



